### PR TITLE
Fill the copyright to LICENSE

### PR DESCRIPTION
**Pull request by pocke**
The company name and year was copied from https://github.com/quipper/i18n-dts#licence .

Thank you for the great product!

### CODE REVIEW

**Review by hotchemi — APPROVED** [review]
Thank you~!

**Review by ohbarye — APPROVED** [review]
Thank you!

**Comment by pocke** [comment]
By the way, I forked this repository to support [react-intl](https://github.com/yahoo/react-intl).
 https://github.com/pocke/react-intl-dts


I mentioned i18n-dts in README and LICENSE, but if you have any problem, feel free to let me know. Thank you!

**Comment by hotchemi** [comment]
Awesome~!

**Pull request merged**
